# Generated by Django 4.1.4 on 2022-12-21 14:10

from django.conf import settings
from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.TextField(default='my study', max_length=100)),
                ('description', models.TextField(default='my description', max_length=1024)),
                ('software', models.CharField(choices=[('JP', 'jsPsych'), ('PS', 'psychoJS'), ('SJ', 'surveyJS')], max_length=2)),
                ('status', models.CharField(choices=[('RU', 'Running'), ('SJ', 'Stopped')], default='SJ', max_length=2)),
                ('researchers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
